version: "{build}"

environment:
  global:
    HAXELIB_ROOT: C:\projects\haxelib

install:
  - haxelib install lime 7.9.0
  - haxelib install openfl
  - haxelib install flixel
  - haxelib install flixel-addons
  - haxelib install flixel-ui
  - haxelib install hscript
  - haxelib install actuate
  - haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit
  - haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
  - haxelib git hxCodec https://github.com/polybiusproxy/hxCodec
  - haxelib git https://github.com/GrowtopiaFli/extension-webm
  - haxelib run lime rebuild extension-webm windows
  - haxelib list

test_script:
  - haxelib run lime test windows
  # haxelib run lime test windows

build_script:
  - haxelib run lime build windows
  # haxelib run lime build linux

artifacts:
  - path: export/release/windows/bin
    name: AlsuhEngine-Windows
    type: zip