version: "{build}"

environment:
  global:
    HAXELIB_ROOT: C:\projects\haxelib

install:
  - haxelib install hmm
  - haxelib run openfl rebuild extension-webm windows
  - haxelib list

test_script:
  - haxelib run openfl test windows

build_script:
  - haxelib run openfl build windows

artifacts:
  - path: export/release/windows/bin
    name: AlsuhEngine-Windows
    type: zip