name: MacOS
on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5
      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib install hxcpp > /dev/null --quiet
          haxelib install hmm --quiet
          haxelib run hmm install
          haxelib run openfl rebuild extension-webm macos
      - name: Compile
        run: haxelib run openfl build macos
      - name: Publish Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: MacOS Build
          path: export/release/macos/bin